apiVersion: v1
kind: Secret
metadata:
  name: test-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  name: test-cluster
  server: arn:aws:eks:ap-southeast-1:830427153490:cluster/test-cluster
  project: default
